Get http://13.234.253.16:7000/api/auth/getDefaultCCEmails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsImVtYWlsIjoiZ2twQGxpdmVmaWJyZS5pbiIsInJvbGVfaWQiOjIsInJvbGUiOiJBZG1pbiIsInN0YXR1cyI6IkFjdGl2ZSIsIndhcmVob3VzZV9pZCI6IjAxOWM0NjQ2LTE0YTctNzZjOC1iNGE2LTU1NDE5YjkwNDQ5YSIsImlhdCI6MTc3NzQzOTYwNSwiZXhwIjoxNzc3NTI2MDA1fQ.h23cwbCytAi05hNDbm3YqtCC6ZHAGLTwsOXrpXrM7sM

###


GEt http://13.234.253.16:7000/api/auth/getDefaultRREmails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsImVtYWlsIjoiZ2twQGxpdmVmaWJyZS5pbiIsInJvbGVfaWQiOjIsInJvbGUiOiJBZG1pbiIsInN0YXR1cyI6IkFjdGl2ZSIsIndhcmVob3VzZV9pZCI6IjAxOWM0NjQ2LTE0YTctNzZjOC1iNGE2LTU1NDE5YjkwNDQ5YSIsImlhdCI6MTc3NzQzOTYwNSwiZXhwIjoxNzc3NTI2MDA1fQ.h23cwbCytAi05hNDbm3YqtCC6ZHAGLTwsOXrpXrM7sM




###


Get http://13.234.253.16:7000/api/auth/getProfileByCode/SecondProduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImVtYWlsIjoic3RvcmVAbWF0cml4bWV0ZXJzLmNvbSIsInJvbGVfaWQiOjIsInJvbGUiOiJBZG1pbiIsInN0YXR1cyI6IkFjdGl2ZSIsIndhcmVob3VzZV9pZCI6IjAxOWJjMGYxLWUwNmQtNzM2Ni05ZjhlLTBmZmI4NDEyNGE0NCIsImlhdCI6MTc3NzUzOTk3MiwiZXhwIjoxNzc3NjI2MzcyfQ.-EHenc-jtefUrU86xjdz26d9YXDZHKuyM0heGl5d-WU


###file
# greater noida admin login 
Get http://13.234.253.16:7000/api/auth/scanProductForTransfer/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImVtYWlsIjoic3RvcmVAbWF0cml4bWV0ZXJzLmNvbSIsInJvbGVfaWQiOjIsInJvbGUiOiJBZG1pbiIsInN0YXR1cyI6IkFjdGl2ZSIsIndhcmVob3VzZV9pZCI6IjAxOWJjMGYxLWUwNmQtNzM2Ni05ZjhlLTBmZmI4NDEyNGE0NCIsImlhdCI6MTc3NzYxMjIxNCwiZXhwIjoxNzc3Njk4NjE0fQ.7r6UI0ZTtvkgtNeCLgbkqDRYXCc-dmBXPxmc7Iaro2s
Content-Type: application/json

# {
#      "product_id": "019ddd22-e489-73f8-90c7-b6b0264556a5"
# }

###
# super admin login 

GET http://13.234.253.16:7000/api/auth/getStockRequestsByUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImVtYWlsIjoic3RvcmVAbWF0cml4bWV0ZXJzLmNvbSIsInJvbGVfaWQiOjIsInJvbGUiOiJBZG1pbiIsInN0YXR1cyI6IkFjdGl2ZSIsIndhcmVob3VzZV9pZCI6IjAxOWJjMGYxLWUwNmQtNzM2Ni05ZjhlLTBmZmI4NDEyNGE0NCIsImlhdCI6MTc3NzQ1MzI5NCwiZXhwIjoxNzc3NTM5Njk0fQ.9f1P80eHjLOvFEzlqSsluIgtA19d-SJbdkrBG2vslZo

