name: Fullstack CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Frontend
        run: npm ci --no-cache
        working-directory: InventoryManagement

      - name: Build Frontend
        run: npm run build
        working-directory: InventoryManagement
